import { config } from "dotenv";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { product } from "@/db/schema";
import { randomBytes } from "crypto";
import { eq } from "drizzle-orm";

config({ path: ".env" });

const sql = neon(process.env.DATABASE_URL as string);
const db = drizzle(sql);

function generateId(): string {
    return randomBytes(16).toString("hex");
}

function slugify(text: string): string {
    return text
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .trim();
}

// Real Pakistan-based bakery products with PKR pricing
const products = [
    // COOKIES
    {
        name: "Nankhatai",
        description: "Traditional Pakistani shortbread cookies made with ghee, flour, and sugar. A classic tea-time favorite that melts in your mouth.",
        shortDescription: "Traditional Pakistani shortbread cookies",
        price: "120",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/nankhatai.jpg",
        images: [],
        category: "cookies",
        calories: 180,
        isActive: true,
        isFeatured: true,
        stock: 75,
    },
    {
        name: "Chocolate Chip Cookies",
        description: "Freshly baked cookies loaded with premium chocolate chips. Crispy on the outside, soft and chewy on the inside.",
        shortDescription: "Classic cookies with premium chocolate chips",
        price: "150",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/chocolate-chip.jpg",
        images: [],
        category: "cookies",
        calories: 200,
        isActive: true,
        isFeatured: true,
        stock: 60,
    },
    {
        name: "Butter Cookies",
        description: "Rich and buttery cookies with a delicate texture. Perfect with a cup of chai.",
        shortDescription: "Rich and buttery traditional cookies",
        price: "100",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/butter-cookies.jpg",
        images: [],
        category: "cookies",
        calories: 170,
        isActive: true,
        isFeatured: false,
        stock: 80,
    },
    {
        name: "Almond Cookies",
        description: "Crunchy cookies made with real almonds and a hint of cardamom. A premium treat for special occasions.",
        shortDescription: "Crunchy almond cookies with cardamom",
        price: "180",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/almond-cookies.jpg",
        images: [],
        category: "cookies",
        calories: 220,
        isActive: true,
        isFeatured: true,
        stock: 50,
    },
    {
        name: "Oatmeal Raisin Cookies",
        description: "Healthy and wholesome cookies made with oats and raisins. A nutritious snack option.",
        shortDescription: "Healthy oatmeal cookies with raisins",
        price: "130",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/oatmeal-raisin.jpg",
        images: [],
        category: "cookies",
        calories: 160,
        isActive: true,
        isFeatured: false,
        stock: 65,
    },
    {
        name: "Sugar Cookies",
        description: "Simple yet delicious sugar cookies with a sweet glaze. Perfect for kids and adults alike.",
        shortDescription: "Classic sweet sugar cookies",
        price: "90",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cookies/sugar-cookies.jpg",
        images: [],
        category: "cookies",
        calories: 150,
        isActive: true,
        isFeatured: false,
        stock: 70,
    },
    
    // SHAKES
    {
        name: "Mango Shake",
        description: "Creamy and refreshing mango shake made with fresh Pakistani mangoes. A perfect summer treat.",
        shortDescription: "Fresh mango shake with cream",
        price: "250",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/mango-shake.jpg",
        images: [],
        category: "shakes",
        calories: 280,
        isActive: true,
        isFeatured: true,
        stock: 40,
    },
    {
        name: "Chocolate Shake",
        description: "Rich and indulgent chocolate shake made with premium cocoa and fresh milk. Topped with whipped cream.",
        shortDescription: "Rich chocolate shake with whipped cream",
        price: "280",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/chocolate-shake.jpg",
        images: [],
        category: "shakes",
        calories: 320,
        isActive: true,
        isFeatured: true,
        stock: 45,
    },
    {
        name: "Strawberry Shake",
        description: "Sweet and tangy strawberry shake made with fresh strawberries. A delightful pink treat.",
        shortDescription: "Fresh strawberry shake",
        price: "270",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/strawberry-shake.jpg",
        images: [],
        category: "shakes",
        calories: 250,
        isActive: true,
        isFeatured: false,
        stock: 35,
    },
    {
        name: "Vanilla Shake",
        description: "Classic vanilla shake with a smooth and creamy texture. Simple yet satisfying.",
        shortDescription: "Classic creamy vanilla shake",
        price: "220",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/vanilla-shake.jpg",
        images: [],
        category: "shakes",
        calories: 240,
        isActive: true,
        isFeatured: false,
        stock: 50,
    },
    {
        name: "Banana Shake",
        description: "Nutritious and filling banana shake made with fresh bananas and milk. A healthy choice.",
        shortDescription: "Fresh banana shake",
        price: "230",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/banana-shake.jpg",
        images: [],
        category: "shakes",
        calories: 200,
        isActive: true,
        isFeatured: false,
        stock: 40,
    },
    {
        name: "Oreo Shake",
        description: "Decadent shake made with crushed Oreo cookies and vanilla ice cream. A cookie lover's dream.",
        shortDescription: "Oreo cookie shake with ice cream",
        price: "300",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/shakes/oreo-shake.jpg",
        images: [],
        category: "shakes",
        calories: 380,
        isActive: true,
        isFeatured: true,
        stock: 30,
    },
    
    // CUPCAKES
    {
        name: "Vanilla Cupcake",
        description: "Moist vanilla cupcake topped with creamy vanilla frosting and colorful sprinkles. Perfect for any occasion.",
        shortDescription: "Classic vanilla cupcake with frosting",
        price: "180",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cupcakes/vanilla-cupcake.jpg",
        images: [],
        category: "cupcakes",
        calories: 220,
        isActive: true,
        isFeatured: true,
        stock: 50,
    },
    {
        name: "Chocolate Cupcake",
        description: "Rich chocolate cupcake with chocolate frosting and chocolate chips. A chocolate lover's delight.",
        shortDescription: "Rich chocolate cupcake",
        price: "200",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cupcakes/chocolate-cupcake.jpg",
        images: [],
        category: "cupcakes",
        calories: 280,
        isActive: true,
        isFeatured: true,
        stock: 45,
    },
    {
        name: "Red Velvet Cupcake",
        description: "Beautiful red velvet cupcake with cream cheese frosting. Elegant and delicious.",
        shortDescription: "Red velvet with cream cheese frosting",
        price: "220",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cupcakes/red-velvet-cupcake.jpg",
        images: [],
        category: "cupcakes",
        calories: 260,
        isActive: true,
        isFeatured: true,
        stock: 40,
    },
    {
        name: "Strawberry Cupcake",
        description: "Fresh strawberry cupcake with strawberry frosting. Light and fruity.",
        shortDescription: "Fresh strawberry cupcake",
        price: "190",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cupcakes/strawberry-cupcake.jpg",
        images: [],
        category: "cupcakes",
        calories: 210,
        isActive: true,
        isFeatured: false,
        stock: 35,
    },
    {
        name: "Lemon Cupcake",
        description: "Zesty lemon cupcake with lemon frosting. Refreshing and tangy.",
        shortDescription: "Zesty lemon cupcake",
        price: "180",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cupcakes/lemon-cupcake.jpg",
        images: [],
        category: "cupcakes",
        calories: 200,
        isActive: true,
        isFeatured: false,
        stock: 30,
    },
    
    // CAKES
    {
        name: "Chocolate Cake (1kg)",
        description: "Rich and moist chocolate cake layered with chocolate buttercream. Perfect for birthdays and celebrations.",
        shortDescription: "Rich chocolate layer cake",
        price: "2500",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/chocolate-cake.jpg",
        images: [],
        category: "cakes",
        calories: 350,
        isActive: true,
        isFeatured: true,
        stock: 20,
    },
    {
        name: "Vanilla Cake (1kg)",
        description: "Classic vanilla cake with vanilla buttercream frosting. Simple, elegant, and delicious.",
        shortDescription: "Classic vanilla layer cake",
        price: "2200",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/vanilla-cake.jpg",
        images: [],
        category: "cakes",
        calories: 320,
        isActive: true,
        isFeatured: true,
        stock: 25,
    },
    {
        name: "Red Velvet Cake (1kg)",
        description: "Beautiful red velvet cake with cream cheese frosting. A showstopper for any occasion.",
        shortDescription: "Red velvet with cream cheese frosting",
        price: "2800",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/red-velvet-cake.jpg",
        images: [],
        category: "cakes",
        calories: 340,
        isActive: true,
        isFeatured: true,
        stock: 15,
    },
    {
        name: "Birthday Cake (1kg)",
        description: "Customizable birthday cake with colorful decorations and your choice of flavor. Make your special day even more special.",
        shortDescription: "Customizable birthday cake",
        price: "3000",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/birthday-cake.jpg",
        images: [],
        category: "cakes",
        calories: 360,
        isActive: true,
        isFeatured: true,
        stock: 10,
    },
    {
        name: "Strawberry Cake (1kg)",
        description: "Fresh strawberry cake with strawberry filling and cream. Light and fruity.",
        shortDescription: "Fresh strawberry layer cake",
        price: "2600",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/strawberry-cake.jpg",
        images: [],
        category: "cakes",
        calories: 310,
        isActive: true,
        isFeatured: false,
        stock: 18,
    },
    {
        name: "Coffee Cake (1kg)",
        description: "Rich coffee-flavored cake with coffee buttercream. Perfect for coffee lovers.",
        shortDescription: "Rich coffee layer cake",
        price: "2400",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/cakes/coffee-cake.jpg",
        images: [],
        category: "cakes",
        calories: 330,
        isActive: true,
        isFeatured: false,
        stock: 12,
    },
    
    // CROISSANTS
    {
        name: "Plain Croissant",
        description: "Buttery and flaky French-style croissant. Perfect for breakfast or as a snack.",
        shortDescription: "Buttery flaky croissant",
        price: "180",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/croissants/plain-croissant.jpg",
        images: [],
        category: "croissants",
        calories: 240,
        isActive: true,
        isFeatured: true,
        stock: 60,
    },
    {
        name: "Chocolate Croissant",
        description: "Flaky croissant filled with rich chocolate. A perfect combination of buttery pastry and chocolate.",
        shortDescription: "Chocolate-filled croissant",
        price: "220",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/croissants/chocolate-croissant.jpg",
        images: [],
        category: "croissants",
        calories: 280,
        isActive: true,
        isFeatured: true,
        stock: 55,
    },
    {
        name: "Almond Croissant",
        description: "Buttery croissant filled with almond paste and topped with sliced almonds. A premium treat.",
        shortDescription: "Almond-filled croissant",
        price: "250",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/croissants/almond-croissant.jpg",
        images: [],
        category: "croissants",
        calories: 300,
        isActive: true,
        isFeatured: true,
        stock: 40,
    },
    {
        name: "Ham & Cheese Croissant",
        description: "Savory croissant filled with ham and cheese. Perfect for a hearty breakfast.",
        shortDescription: "Ham and cheese croissant",
        price: "240",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/croissants/ham-cheese-croissant.jpg",
        images: [],
        category: "croissants",
        calories: 320,
        isActive: true,
        isFeatured: false,
        stock: 35,
    },
    
    // BREADS
    {
        name: "White Bread (Loaf)",
        description: "Fresh white bread baked daily. Soft, fluffy, and perfect for sandwiches and toast.",
        shortDescription: "Fresh white bread loaf",
        price: "150",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/white-bread.jpg",
        images: [],
        category: "breads",
        calories: 80,
        isActive: true,
        isFeatured: true,
        stock: 80,
    },
    {
        name: "Brown Bread (Loaf)",
        description: "Healthy whole wheat bread with a nutty flavor. Great for a nutritious breakfast.",
        shortDescription: "Whole wheat brown bread",
        price: "180",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/brown-bread.jpg",
        images: [],
        category: "breads",
        calories: 90,
        isActive: true,
        isFeatured: true,
        stock: 70,
    },
    {
        name: "Naan (4 pieces)",
        description: "Traditional Pakistani naan baked in tandoor. Soft, fluffy, and perfect with curry or kebabs.",
        shortDescription: "Traditional tandoori naan",
        price: "120",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/naan.jpg",
        images: [],
        category: "breads",
        calories: 150,
        isActive: true,
        isFeatured: true,
        stock: 100,
    },
    {
        name: "Garlic Bread (Loaf)",
        description: "Aromatic garlic bread with herbs and butter. Perfect as a side dish or snack.",
        shortDescription: "Garlic and herb bread",
        price: "200",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/garlic-bread.jpg",
        images: [],
        category: "breads",
        calories: 200,
        isActive: true,
        isFeatured: false,
        stock: 45,
    },
    {
        name: "Multigrain Bread (Loaf)",
        description: "Nutritious multigrain bread with seeds and grains. A healthy choice for daily consumption.",
        shortDescription: "Healthy multigrain bread",
        price: "220",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/multigrain-bread.jpg",
        images: [],
        category: "breads",
        calories: 100,
        isActive: true,
        isFeatured: false,
        stock: 50,
    },
    {
        name: "Roti (10 pieces)",
        description: "Fresh homemade roti, a staple of Pakistani cuisine. Soft and perfect with any meal.",
        shortDescription: "Fresh homemade roti",
        price: "100",
        originalPrice: null,
        image: "https://res.cloudinary.com/demo/image/upload/v1/breads/roti.jpg",
        images: [],
        category: "breads",
        calories: 70,
        isActive: true,
        isFeatured: false,
        stock: 90,
    },
];

async function seedProducts() {
    try {
        console.log("🌱 Starting product seeding...");

        // Clear existing products
        console.log("🗑️  Clearing existing products...");
        const existingProducts = await db.select().from(product);
        for (const existing of existingProducts) {
            await db.delete(product).where(eq(product.id, existing.id));
        }

        // Insert new products
        console.log(`📦 Inserting ${products.length} products...`);
        for (const productData of products) {
            const slug = slugify(productData.name);
            const productId = generateId();

            await db.insert(product).values({
                id: productId,
                name: productData.name,
                slug,
                description: productData.description,
                shortDescription: productData.shortDescription,
                price: productData.price,
                originalPrice: productData.originalPrice,
                image: productData.image,
                images: productData.images,
                category: productData.category,
                calories: productData.calories,
                isActive: productData.isActive,
                isFeatured: productData.isFeatured,
                stock: productData.stock,
            });

            console.log(`✅ Added: ${productData.name}`);
        }

        console.log(`\n✨ Successfully seeded ${products.length} products!`);
    } catch (error) {
        console.error("❌ Error seeding products:", error);
        process.exit(1);
    }
}

seedProducts();
